- week: 

- week:

- week: 
    
- week: 
    
- week: Team Setup
  handout: 01/
  rubric:
      - deliverable: https://grademy.work/rubric?id=C01F18-D1
      - interview: https://grademy.work/rubric?id=C01F18-I1

- break: <span class="em">Reading Week</span>    
    
- week: Project Requirement
  handout: 02/
  rubric:
    - deliverable: https://grademy.work/rubric?id=C01F18-D2
    - interview: https://grademy.work/rubric?id=C01F18-I2

- week: 
    
- week: Project Planning and Execution
  handout: 03/
  rubric:
      - deliverable: https://grademy.work/rubric?id=C01F18-D3
      - interview: https://grademy.work/rubric?id=C01F18-I3
  
- week: 

- week: Verification and Code Review
  handout: 04/
  rubric:
      - deliverable: https://grademy.work/rubric?id=C01F18-D4
      - interview: https://grademy.work/rubric?id=C01F18-I4

- week: 
  
- week: Final Deliverable
  handout: 05/
  rubric:
      - deliverable: https://grademy.work/rubric?id=C01F18-D5
      - interview: https://grademy.work/rubric?id=C01F18-I5
