- week: 

- week:

- week: 
    
- week: 
    
- week: Team Setup
  handout: 01/
  # rubric:
  #     - deliverable: https://grademy.work/rubric?id=C01F17-D1
  #     - interview: https://grademy.work/rubric?id=C01F17-I1


- break: <span class="em">Reading Week</span>    
    
- week: Project Requirement
  handout: 02/
  # rubric:
  #   - deliverable: https://grademy.work/rubric?id=C01F17-D2
  #   - interview: https://grademy.work/rubric?id=C01F17-I2
    
- week: Project Planning
  # handout: 07/
  # rubric:
  #     - deliverable: https://grademy.work/rubric?id=C01F17-D3
  #     - interview: https://grademy.work/rubric?id=C01F17-I3

- week: 
    
- week: Project Execution

  # handout: 09/
  # rubric:
  #     - deliverable: https://grademy.work/rubric?id=C01F17-D4
  #     - interview: https://grademy.work/rubric?id=C01F17-I4
  
- week: 

- week: Product Validation

  # handout: 11/
  # rubric:
  #     - deliverable: https://grademy.work/rubric?id=C01F17-D5
  #     - interview: https://grademy.work/rubric?id=C01F17-I5
  
- week: Final Deliverable
